apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sprayproxy-api-reader
rules:
  - nonResourceURLs:
      - "/metrics"
      - "/unregister"
    verbs:
      - get
  - nonResourceURLs:
      - "/register"
    verbs:
      - create
